site_name: "Q:\\>qwinsta_"
site_url: https://qwinsta.ru/

theme:
  name: material
  language: ru
  favicon: assets/favicon.png

  icon:
    logo: material/console

  palette:
    scheme: slate
    primary: black
    accent: green

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luckygoodwin/qwinsta

nav:
  - Главная: index.md