site_name: "Q:\\>qwinsta_"
site_url: https://qwinsta.ru/

theme:
  name: material
  language: ru

  icon:
    logo: material/console

  palette:
    scheme: slate
    primary: black
    accent: green

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - "Главная": index.md

  - "Docs":
      - "GitHub Pages + MkDocs": github-pages-mkdocs.md

  - "VPN":
      - "OpenVPN на Windows Server 2022": vpn/openvpn/install-windows-server.md
      - "WireGuard Site-to-Site (MikroTik)": vpn/wireguard/wireguard-site-to-site-mikrotik.md
      - "XRay + Reality + 3x-ui": vpn/xray/xray-reality.md
      - "MTProxy + Fake TLS + Sponsor Bot": vpn/mtproxy/fake-tls.md
      - "Tinyproxy HTTP Proxy": vpn/tinyproxy/install.md

  - "Windows":
      - "Обзор": windows/index.md
      - "RDP":
          - "Обзор": windows/rdp/index.md
          - "Event ID 4625": windows/rdp/event-id-4625.md